{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "acb93fe6-bb65-4662-afc3-81504dec3e25",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 0 235 Loss: 2.300 | Acc: 11.328% (29/256)\n",
      "0 50 235 Loss: 2.303 | Acc: 10.355% (1352/13056)\n",
      "0 100 235 Loss: 2.301 | Acc: 11.699% (3025/25856)\n",
      "0 150 235 Loss: 2.300 | Acc: 11.584% (4478/38656)\n"
     ]
    }
   ],
   "source": [
    "# 该代码在LeNet模型训练过程中加入了argparse库的使用\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import argparse\n",
    "\n",
    "from torchvision.datasets import MNIST\n",
    "import torchvision.transforms as transforms\n",
    "from torch.utils.data import DataLoader\n",
    "\n",
    "parser=argparse.ArgumentParser(description=\"PyTorch LeNet Traning\")\n",
    "\n",
    "parser.add_argument (\"--lr\", default=0.01,type=float,help=\"Learning rate\")\n",
    "\n",
    "parser.add_argument (\"--batch-size\", \"-b\", default=256,type=int,help=\"Batchsize\")\n",
    "\n",
    "parser.add_argument (\"--epoch\", default=4,type=int,help=\"Epoch\")\n",
    "\n",
    "args=parser.parse_args(args=[])\n",
    "\n",
    "batch_size = args.batch_size\n",
    "lr = args.lr # 定义学习率\n",
    "epochs = args.epoch # 定义训练迭代期\n",
    "# 训练数据载入器\n",
    "data_train = MNIST(\"./data\",\n",
    "                    download=True,\n",
    "                    transform=transforms.Compose([\n",
    "                        transforms.Resize((32, 32)),\n",
    "                        transforms.ToTensor()]))\n",
    "data_test = MNIST(\"./data\",\n",
    "                    train=False,\n",
    "                    download=True,\n",
    "                    transform=transforms.Compose([\n",
    "                        transforms.Resize((32, 32)),\n",
    "                        transforms.ToTensor()]))\n",
    "data_train_loader = DataLoader(data_train, batch_size=batch_size,\n",
    "    shuffle=True, num_workers=2)\n",
    "data_test_loader = DataLoader(data_test, batch_size=batch_size,\n",
    "    num_workers=2)\n",
    "\n",
    "class LeNet(nn.Module):\n",
    "\n",
    "    def __init__(self):\n",
    "        super(LeNet, self).__init__()\n",
    "        self.conv1 = nn.Conv2d(1, 6, 3)\n",
    "        self.pool1 = nn.MaxPool2d(2, 2)\n",
    "        self.conv2 = nn.Conv2d(6, 16, 3)\n",
    "        self.pool2 = nn.MaxPool2d(2, 2)\n",
    "        self.fc3 = nn.Linear(16*6*6, 120)\n",
    "        self.fc4 = nn.Linear(120, 84)\n",
    "        self.fc5 = nn.Linear(84, 10)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.pool1(torch.relu(self.conv1(x)))\n",
    "        x = self.pool2(torch.relu(self.conv2(x)))\n",
    "        x = x.view(x.size(0), -1)\n",
    "        x = torch.relu(self.fc3(x))\n",
    "        x = torch.relu(self.fc4(x))\n",
    "        x = self.fc5(x)\n",
    "        return x\n",
    "\n",
    "def train():\n",
    "    model = LeNet() # 定义LeNet模型\n",
    "    model.train() # 切换模型到训练状态\n",
    "\n",
    "    criterion = nn.CrossEntropyLoss() # 定义损失函数\n",
    "    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0.9,\n",
    "                         weight_decay=5e-4) #定义随机梯度下降优化器\n",
    "\n",
    "    for epoch in range(epochs):\n",
    "        train_loss = 0\n",
    "        correct = 0\n",
    "        total = 0\n",
    "        for batch_idx, (inputs, targets) in enumerate(data_train_loader):\n",
    "            optimizer.zero_grad()\n",
    "            outputs = model(inputs)\n",
    "            loss = criterion(outputs, targets)\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "\n",
    "            train_loss += loss.item()\n",
    "            _, predicted = outputs.max(1)\n",
    "            total += targets.size(0)\n",
    "            correct += predicted.eq(targets).sum().item()\n",
    "\n",
    "            if batch_idx % 50 == 0 or batch_idx == (len(data_train_loader) - 1):\n",
    "                print(epoch, batch_idx, len(data_train_loader), \"Loss: %.3f | Acc: %.3f%% (%d/%d)\"\n",
    "                     % (train_loss / (batch_idx + 1), 100. * correct / total, correct, total))\n",
    "    # 模型的保存\n",
    "    torch.save(model.state_dict(), \"model_lenet_epoch.pth\")  # 模型的状态字典\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    train()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2be08a33-ce58-4d9a-881d-9ee082fe04f3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
