{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d30370b6-4aa1-4424-8cdb-0a51271ccd69",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 该代码定义了LeNet模型\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "\n",
    "class LeNet(nn.Module):\n",
    "\n",
    "    def __init__(self):\n",
    "        super(LeNet, self).__init__()\n",
    "        self.conv1 = nn.Conv2d(1, 6, 3)\n",
    "        self.pool1 = nn.MaxPool2d(2, 2)\n",
    "        self.conv2 = nn.Conv2d(6, 16, 3)\n",
    "        self.pool2 = nn.MaxPool2d(2, 2)\n",
    "        self.fc3 = nn.Linear(16*6*6, 120)\n",
    "        self.fc4 = nn.Linear(120, 84)\n",
    "        self.fc5 = nn.Linear(84, 10)\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.pool1(torch.relu(self.conv1(x)))\n",
    "        x = self.pool2(torch.relu(self.conv2(x)))\n",
    "        x = x.view(x.size(0), -1)\n",
    "        x = torch.relu(self.fc3(x))\n",
    "        x = torch.relu(self.fc4(x))\n",
    "        x = self.fc5(x)\n",
    "        return x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "fe6462cb-bc1d-4f5e-964c-e6a74339a78d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 10 Loss: 0.477 | Acc: 83.887% (859/1024)\n",
      "1 10 Loss: 0.535 | Acc: 83.008% (1700/2048)\n",
      "2 10 Loss: 0.532 | Acc: 83.105% (2553/3072)\n",
      "3 10 Loss: 0.541 | Acc: 82.642% (3385/4096)\n",
      "4 10 Loss: 0.530 | Acc: 83.066% (4253/5120)\n",
      "5 10 Loss: 0.503 | Acc: 83.936% (5157/6144)\n",
      "6 10 Loss: 0.483 | Acc: 84.738% (6074/7168)\n",
      "7 10 Loss: 0.475 | Acc: 84.814% (6948/8192)\n",
      "8 10 Loss: 0.455 | Acc: 85.449% (7875/9216)\n",
      "9 10 Loss: 0.457 | Acc: 85.500% (8550/10000)\n"
     ]
    }
   ],
   "source": [
    "# 该代码定义了LeNet模型的推断过程\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "# from model import LeNet # 若放入工程文件时，需要使用此命令\n",
    "\n",
    "# 该段代码用于leNet的训练数据集MNIST的载入\n",
    "\n",
    "from torchvision.datasets import MNIST\n",
    "import torchvision.transforms as transforms\n",
    "from torch.utils.data import DataLoader\n",
    "\n",
    "data_train = MNIST(\"./data\",\n",
    "                    download=True,\n",
    "                    transform=transforms.Compose([\n",
    "                        transforms.Resize((32, 32)),\n",
    "                        transforms.ToTensor()\n",
    "                    ]))\n",
    "data_test = MNIST(\"./data\",\n",
    "                    train=False,\n",
    "                    download=True,\n",
    "                    transform=transforms.Compose([\n",
    "                        transforms.Resize((32, 32)),\n",
    "                        transforms.ToTensor()\n",
    "                    ]))\n",
    "\n",
    "data_train_loader = DataLoader(data_train, batch_size=256,\n",
    "    shuffle=True, num_workers=2)\n",
    "data_test_loader = DataLoader(data_test, batch_size=1024,\n",
    "    num_workers=2)\n",
    "\n",
    "# 假设模型保存在model_lenet_pth文件中，也可选择多迭代期训练的模型model_lenet_epoch.pth\n",
    "model_path = \"./model_lenet.pth\"\n",
    "model = LeNet() #定义LeNet模型\n",
    "criterion = nn.CrossEntropyLoss() #定义损失函数\n",
    "model.load_state_dict(torch.load(model_path)) # 载入模型和参数\n",
    "\n",
    "test_loss = 0\n",
    "correct = 0\n",
    "total = 0\n",
    "with torch.no_grad(): # 关闭计算图\n",
    "    for batch_idx, (inputs, targets) in enumerate(data_test_loader):\n",
    "\n",
    "        outputs = model(inputs)\n",
    "        loss = criterion(outputs, targets)\n",
    "\n",
    "        test_loss += loss.item()\n",
    "        _, predicted = outputs.max(1)\n",
    "        total += targets.size(0)\n",
    "        correct += predicted.eq(targets).sum().item()\n",
    "\n",
    "        print(batch_idx, len(data_test_loader), \"Loss: %.3f | Acc: %.3f%% (%d/%d)\"\n",
    "             % (test_loss/(batch_idx+1), 100.*correct/total, correct, total))\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b85e1aae-725b-4305-9b37-1f7d88a912f5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 10 Loss: 0.477 | Acc: 83.887% (859/1024)\n",
      "1 10 Loss: 0.535 | Acc: 83.008% (1700/2048)\n",
      "2 10 Loss: 0.532 | Acc: 83.105% (2553/3072)\n",
      "3 10 Loss: 0.541 | Acc: 82.642% (3385/4096)\n",
      "4 10 Loss: 0.530 | Acc: 83.066% (4253/5120)\n",
      "5 10 Loss: 0.503 | Acc: 83.936% (5157/6144)\n",
      "6 10 Loss: 0.483 | Acc: 84.738% (6074/7168)\n",
      "7 10 Loss: 0.475 | Acc: 84.814% (6948/8192)\n",
      "8 10 Loss: 0.455 | Acc: 85.449% (7875/9216)\n",
      "9 10 Loss: 0.457 | Acc: 85.500% (8550/10000)\n"
     ]
    }
   ],
   "source": [
    "# 该代码定义了LeNet模型的推断过程\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "# from model import LeNet # 若放入工程文件时，需要使用此命令\n",
    "\n",
    "# 该段代码用于leNet的训练数据集MNIST的载入\n",
    "\n",
    "from torchvision.datasets import MNIST\n",
    "import torchvision.transforms as transforms\n",
    "from torch.utils.data import DataLoader\n",
    "\n",
    "data_train = MNIST(\"./data\",\n",
    "                    download=True,\n",
    "                    transform=transforms.Compose([\n",
    "                        transforms.Resize((32, 32)),\n",
    "                        transforms.ToTensor()\n",
    "                    ]))\n",
    "data_test = MNIST(\"./data\",\n",
    "                    train=False,\n",
    "                    download=True,\n",
    "                    transform=transforms.Compose([\n",
    "                        transforms.Resize((32, 32)),\n",
    "                        transforms.ToTensor()\n",
    "                    ]))\n",
    "\n",
    "data_train_loader = DataLoader(data_train, batch_size=256,\n",
    "    shuffle=True, num_workers=2)\n",
    "data_test_loader = DataLoader(data_test, batch_size=1024,\n",
    "    num_workers=2)\n",
    "\n",
    "# 假设模型保存在model_lenet_pth文件中，也可选择多迭代期训练的模型model_lenet_epoch.pth\n",
    "model_path = \"./model_lenet.pth\"\n",
    "model = LeNet() #定义LeNet模型\n",
    "criterion = nn.CrossEntropyLoss() #定义损失函数\n",
    "model.load_state_dict(torch.load(model_path)) # 载入模型和参数\n",
    "model.eval() # 切换模型到测试状态\n",
    "\n",
    "test_loss = 0\n",
    "correct = 0\n",
    "total = 0\n",
    "with torch.no_grad(): # 关闭计算图\n",
    "    for batch_idx, (inputs, targets) in enumerate(data_test_loader):\n",
    "\n",
    "        outputs = model(inputs)\n",
    "        loss = criterion(outputs, targets)\n",
    "\n",
    "        test_loss += loss.item()\n",
    "        _, predicted = outputs.max(1)\n",
    "        total += targets.size(0)\n",
    "        correct += predicted.eq(targets).sum().item()\n",
    "\n",
    "        print(batch_idx, len(data_test_loader), \"Loss: %.3f | Acc: %.3f%% (%d/%d)\"\n",
    "             % (test_loss/(batch_idx+1), 100.*correct/total, correct, total))\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cdb0793e-37de-4285-b434-75e80f0f47eb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
